### ISSUE TITLE
List of "complex" feeds

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#107]
I am prioritizing work to reduce the backlog of feeds, and to approve recently-submitted feeds. Anything complex (bad URL, requires discussion, missing information) is relegated to the add after all "simple" feeds are added to the registry. 

When I have background information or research on the feed, I will create a new ticket for that feed.

**Self-created or unofficial**
- [x] [Carlsbad, NM](https://transit.land/dispatcher/changesets/2186) - see #86 
- [x] [Estonia](https://transit.land/dispatcher/changesets/1530)
- [x] [Milan Malpensa airport](https://transit.land/dispatcher/changesets/1299) - see #125 
- [x] [Jawa Barat, Indonesia](https://transit.land/dispatcher/changesets/2184)

**Hosted in weird places**
- [x] [SNCF Intercités](https://transit.land/dispatcher/changesets/1506) - see #109 
- [x] [Gaborone, Botswana](https://transit.land/dispatcher/changesets/1257) - feed not found; changeset deleted as I couldn't find another source for this
- [ ] [Corvatsch, Silvaplana, Switzerland](https://transit.land/dispatcher/changesets/2322) - hosted on Dropbox, and [another one](https://transit.land/dispatcher/changesets/2322) is hosted on Google Drive

**Not transit**
- [x] [Blue & Gold Fleet](https://transit.land/dispatcher/changesets/2181) - see #111 

**Other**
- Feeds from Translink in Australia. This requires more investigation as to what relationship the "Translink" name has to the different feeds. It seems to be a common brand. See #76

**Comment by stevevance** [comment]
The Blue & Gold Fleet was deleted. This was for a tourist boat ride, not transit, so it was inappropriate for Transitland.

**Comment by stevevance** [comment]
Corvatsch should be removed per #194
