### ISSUE TITLE
new version of Caltrain feed doesn't include shapes

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#12]
but still includes `shape_id` column in `trips.txt`

also looks like the `agency_id` field changed in `agencies.txt`

http://www.caltrain.com/Assets/GTFS/caltrain/GTFS-Caltrain-Devs.zip version posted on Jan. 25, 2016

TODO:

- [x] @irees: gracefully ignore in https://github.com/transitland/gtfs/issues/18 and https://github.com/transitland/transitland-datastore/pull/340
- [x] @doublestranded: debug why `RouteStopPattern`s are failing in Feed Eater: https://github.com/transitland/transitland-datastore/issues/339 actually a red herring
- [x] @irees: if agency ID changes in a GTFS feed, fail gracefully and log the error: https://github.com/transitland/transitland-datastore/issues/356
- [ ] Drew: write to Caltrain and/or MTC to ask them to add back `shapes.txt` in the future
