### ISSUE TITLE
Remaining "never imported" feeds

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#198]
I've spent the last two weeks trying to import every remaining feed that has a status of `never_imported` in the Dispatcher and these are the ones that still remain. 

- [x] [Tri-Rail](https://transit.land/dispatcher/feeds/f-dhx-tri~rail) - need to [change](https://transit.land/dispatcher/changesets/3584) the agency ID but it has [an issue](https://github.com/transitland/transitland/issues/186) - this will be resolved in the next dev to production release. 
- [x] A Finnish feed, see issue #180 
- [ ] Emory university, see issue #192 - feed is invalid
- [ ] [Berlin/Brandenburg](https://transit.land/dispatcher/feeds/f-u3-günterangergüterverkehrsgmbh~coomnibusvermietungkg~fritzbeh) - requires a larger instance
- [ ] [Great Britain rail](https://transit.land/dispatcher/feeds/f-gc-arrivatrainswales~c2c~chilternrailways~crosscountry~eastcoa) - requires a larger instance to import
- [x] [France TER](https://transit.land/dispatcher/feeds/f-u0-sncf~ter) - [problem importing](https://transit.land/dispatcher/feeds/f-u0-sncf~ter)
- [x] [France Intercités](https://transit.land/dispatcher/feeds/f-u-sncf~intercites) - to be removed, see issue #197 
- [x] [Paris Transilien](https://transit.land/dispatcher/feeds/f-u0-sncf~transilien) - to be selectively imported, see issue #197 
- [x]  Lewiston, Idaho - [won't fetch](https://transit.land/dispatcher/feeds/f-c2hzc-lewistontransitsystem) - try again after latest deploy
- [ ]  Lublin, Poland - [feed not found, 404](https://transit.land/dispatcher/feeds/f-u905-lublin) and I can't find a new one 
- [ ] Mottarone/Mottrone, Italy - [feed not found, 404](https://transit.land/dispatcher/feeds/f-u0nj1-mtt) and I can't find a new one. Detach feed from operator?
- [ ] Bormio, Italy - [feed not found, 404](https://transit.land/dispatcher/feeds/f-u0r27-societacooperativatrasportibormio) and I can't find a new one. Detach feed from operator?
- [ ] Cleveland - cannot currently [apply this changeset](https://transit.land/dispatcher/changesets/3752) - try again after latest deploy
- [x] Melbourne 1/3: [can't fetch this feed](https://transit.land/dispatcher/feeds/f-r1r-ptv~2)
- [x] Melbourne 2/3: [can't fetch this feed](https://transit.land/dispatcher/feeds/f-r1r-ptv~4)
- [x] Melbourne 3/3: [can't fetch this feed](https://transit.land/dispatcher/feeds/f-r1-ptv~3)

This excludesl Switzerland, Netherlands, Los Angeles, and a couple of hours because other issues describe problems with those feeds.

**Comment by stevevance** [comment]
Not every feed is checked off above because it has problems.
