### ISSUE TITLE
feed-level improvements

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#218]
We're planning a set of improvements across all of the components of Transitland in order to make the platform more useful to producers and consumers of GTFS feeds.

use case: Feed producers want to check to make sure their feeds are listed in Transitland. They may be responsible for multiple feeds and want to see which are already listed and which need to be added.
- [ ] Datastore API: allow look-up of feeds by their source URL(s): https://github.com/transitland/transitland-datastore/issues/1010
- [ ] Dispatcher admin interface: take in a list of URLs are return which are registered feeds and which need to be added (with prepared links to Feed Registry "add a feed" flow)

use case: Feed producers or consumers want to quickly learn more about the contents of a feed in order to debug potential problems.
- [ ] run Google Python FeedValidator on all new feeds fetched: https://github.com/transitland/transitland-datastore/issues/888 (we've added this previously but it hasn't been a reliable process)
- [ ] run Conveyal Java GTFS Validator on all new feeds fetched: https://github.com/transitland/transitland-datastore/issues/888
- [ ] Dispatcher: show the output from Conveyal GTFS Validator: https://github.com/conveyal/gtfs-validator/tree/master/gtfs-validator-webapp
- [ ] Feed Registry: links to view validation reports
- [ ] Datastore: collect and store descriptive stats on each feed version: https://github.com/transitland/transitland-datastore/issues/646
- [ ] Dispatcher: display feed version descriptive stats

**Comment by drewda** [comment]
Blog posts:
- [ ] feed reports: https://github.com/mapzen/website/pull/1656
